### ISSUE TITLE
Additional content-db bugs

### ISSUE THREAD

**Issue by PsiLupan** [n15g/badger#28]
I've recently created a fork of the Homecoming content db for Thunderspy and added it as a new content-db, which is visible at https://psilupan.github.io/badger/ 

I've noticed the following after adding the package and loading it via the following new lines in the content-db.service.ts constructor:

```
this.contentDb.load(new Thunderspy());
this.contentDb.load(new ThunderspyBadges());
this.contentDb.load(new ThunderspyChangelog());
```

The server shows under the Badges dropdown, but changing between Homecoming and Thunderspy leads to a filter based off the previous page. IE. Homecoming -> Thunderspy leads to a negative filter.

Likewise, attempting to create a new character leads to an invalid key error for loading the Archetype image data when looking at the console log. I'm unsure what the cause is here as break-pointing seems to indicate no serverGroup is available and the key is thus null, as the only line removed was that for Sentinel in the array.

**Comment by PsiLupan** [comment]
Just to verify, I loaded up *without* Homecoming loaded in the contentDB constructor, and everything works as expected.

**Comment by n15g** [comment]
There seems to be a few issues with multiple server groups... oversights since it's never really been implemented. I can't even test it locally because I'm getting some weird issue with the popper.js dropdown in the main menu.
I'm a bit busy at the moment, but I'll try and get some time to look into these issues further as soon as I can.
